In [1]:
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import torch
from torch_geometric.nn import Node2Vec
from torch_geometric.datasets import Planetoid

In [2]:
num_nodes = 3
embedding = torch.nn.Embedding(num_nodes, 2)
sample_path = torch.LongTensor([0, 1, 2, 1])  # pathの長さは任意
Z = embedding(sample_path)
print(Z.shape)
Z

torch.Size([4, 2])


tensor([[ 0.6069, -0.6366],
        [ 0.3909, -0.1595],
        [-0.4410,  0.4885],
        [ 0.3909, -0.1595]], grad_fn=<EmbeddingBackward0>)

In [5]:
import numpy as np
matrix = np.random.random([num_nodes, 2])  # 64-dimensional embeddings
print(matrix)
ids = np.array([0, 1, 2, 1])
matrix[ids]  # prints a matrix of shape [4, 64] 

[[0.95552694 0.94687396]
 [0.02483865 0.7005039 ]
 [0.20866118 0.60114873]]


array([[0.95552694, 0.94687396],
       [0.02483865, 0.7005039 ],
       [0.20866118, 0.60114873],
       [0.02483865, 0.7005039 ]])